version: '3'

services:
  cache:
    image: redis:5-alpine
    restart: unless-stopped
    ports:
      - 6379:6379

  db:
    image: postgres:11-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./volumes/database:/var/lib/postgresql/data

  # AWS SDK works good enough
  # storage:
  #   image: minio/minio
  #   command: minio gateway s3 ${STORAGE_HOST}
  #   restart: unless-stopped
  #   environment:
  #     MINIO_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
  #     MINIO_SECRET_KEY: ${STORAGE_SECRET_KEY}
  #   ports:
  #     - 9000:9000

  log-db:
    image: mongo:4
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: ${LOG_DB_DATABASE}
      # MONGO_INITDB_ROOT_USERNAME: ${LOG_DB_USER}
      # MONGO_INITDB_ROOT_PASSWORD: ${LOG_DB_PASSWORD}
    volumes:
      - ./volumes/log-database:/data/db
