version: '3'

services:
  cache:
    image: redis:5-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - my_subs_network

  db:
    image: postgres:11-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    networks:
      - my_subs_network

  log-db:
    image: mongo:4
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: ${LOG_DB_DATABASE}
      # MONGO_INITDB_ROOT_USERNAME: ${LOG_DB_USER}
      # MONGO_INITDB_ROOT_PASSWORD: ${LOG_DB_PASSWORD}
    volumes:
      - ./volumes/log-database:/data/db
    networks:
      - my_subs_network

networks:
  my_subs_network:
