version: '3'

services:
  cache:
    image: redis:5-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - my_subs_network

  db:
    container_name: 'my_sub_pg'
    image: postgres:11-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    networks:
      - my_subs_network

networks:
  my_subs_network:
