import { SerializeOptions } from '@nestjs/common';
import { Exclude } from 'class-transformer';
import { IsDate, IsPositive, IsNumber, Min } from 'class-validator';
import { Field, ID, ObjectType } from 'type-graphql';
import {
  Column,
  CreateDateColumn,
  Entity,
  PrimaryGeneratedColumn,
  UpdateDateColumn
} from 'typeorm';
import { User } from '../user/user.entity';
import { Company } from '../company/company.entity';
import moment = require('moment');

@ObjectType()
@Entity('users')
@SerializeOptions({ enableCircularCheck: true })
export class Subscription {
  /* Autogenerated unique ID */
  @PrimaryGeneratedColumn('uuid')
  @Field(type => ID)
  id: string;

  /* Company where subscription is valid */
  @Column()
  @Field()
  company: Company;

  /* Subscription owner */
  @Column()
  @Field()
  owner: User;

  /* Date from which subscription is valid */
  @Column()
  @Field()
  @IsDate()
  from: Date;

  /* Date to which subscription is valid */
  @Column()
  @Field()
  @IsDate()
  to: Date;

  /* How much did this subscription cost */
  @Column()
  @Field()
  @IsNumber()
  @Min(0)
  price: number;

  /* When was subscription updated */
  @UpdateDateColumn()
  @Exclude()
  updatedAt: Date;

  /* When was subscription created */
  @CreateDateColumn()
  @Exclude()
  createdAt: Date;

  /**
   * Set how long subscription is valid, and when it starts.
   * Default is one month, and starts now
   */
  setDuration(
    duration: moment.Duration = moment.duration(1, 'month'),
    timeFrom: moment.Moment = moment()
  ) {
    this.from = timeFrom.toDate();
    this.to = timeFrom
      .add(duration)
      .subtract(1, 'day')
      .endOf('day')
      .toDate();
  }
}
